# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: console

release:
   name_template: "Release version {{.Tag}}"
   github:
    owner: minio
    name: console
   extra_files:
     - glob: "*.minisig"

before:
  hooks:
    # you may remove this if you don't use vgo
    - go mod tidy

builds:
  -
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - ppc64le
      - s390x
      - arm64
    ignore:
      - goos: darwin
        goarch: arm
      - goos: windows
        goarch: arm64
      - goos: windows
        goarch: arm

    env:
      - CGO_ENABLED=0

    main: ./cmd/console/

    flags:
      - -trimpath
      - --tags=kqueue,operator

    ldflags:
      - -s -w -X github.com/foroughfor/console/pkg.ReleaseTag={{.Tag}} -X github.com/foroughfor/console/pkg.CommitID={{.FullCommit}} -X github.com/foroughfor/console/pkg.Version={{.Version}} -X github.com/foroughfor/console/pkg.ShortCommitID={{.ShortCommit}} -X github.com/foroughfor/console/pkg.ReleaseTime={{.Date}}

archives:
  -
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
    format: binary
    replacements:
      arm: arm

signs:
  -
    signature: "${artifact}.minisig"
    cmd: "sh"
    args:
      - '-c'
      - 'minisign -s /media/${USER}/minio/minisign.key -Sm ${artifact} < /media/${USER}/minio/minisign-passphrase'
    artifacts: all

snapshot:
  name_template: v0.0.0@{{.ShortCommit}}

changelog:
  sort: asc

nfpms:
  -
    vendor: MinIO, Inc.
    homepage: https://github.com/foroughfor/console
    maintainer: MinIO Development <dev@min.io>
    description: MinIO Console Server
    license: GNU Affero General Public License v3.0
    formats:
      - deb
      - rpm
    contents:
      # Basic file that applies to all packagers
      - src: systemd/console.service
        dst: /etc/systemd/system/minio-console.service

dockers:
- image_templates:
  - "foroughfor/console:{{ .Tag }}-amd64"
  use: buildx
  goarch: amd64
  dockerfile: Dockerfile.release
  extra_files:
    - LICENSE
    - CREDITS
  build_flag_templates:
  - "--platform=linux/amd64"
  - "--build-arg=TAG={{ .Tag }}"
- image_templates:
  - "foroughfor/console:{{ .Tag }}-ppc64le"
  use: buildx
  goarch: ppc64le
  dockerfile: Dockerfile.release
  extra_files:
    - LICENSE
    - CREDITS
  build_flag_templates:
  - "--platform=linux/ppc64le"
  - "--build-arg=TAG={{ .Tag }}"
- image_templates:
  - "foroughfor/console:{{ .Tag }}-s390x"
  use: buildx
  goarch: s390x
  dockerfile: Dockerfile.release
  extra_files:
    - LICENSE
    - CREDITS
  build_flag_templates:
  - "--platform=linux/s390x"
  - "--build-arg=TAG={{ .Tag }}"
- image_templates:
  - "foroughfor/console:{{ .Tag }}-arm64"
  use: buildx
  goarch: arm64
  goos: linux
  dockerfile: Dockerfile.release
  extra_files:
    - LICENSE
    - CREDITS
  build_flag_templates:
  - "--platform=linux/arm64"
  - "--build-arg=TAG={{ .Tag }}"
- image_templates:
  - "quay.io/foroughfor/console:{{ .Tag }}-amd64"
  use: buildx
  goarch: amd64
  dockerfile: Dockerfile.release
  extra_files:
    - LICENSE
    - CREDITS
  build_flag_templates:
  - "--platform=linux/amd64"
  - "--build-arg=TAG={{ .Tag }}"
- image_templates:
  - "quay.io/foroughfor/console:{{ .Tag }}-ppc64le"
  use: buildx
  goarch: ppc64le
  dockerfile: Dockerfile.release
  extra_files:
    - LICENSE
    - CREDITS
  build_flag_templates:
  - "--platform=linux/ppc64le"
  - "--build-arg=TAG={{ .Tag }}"
- image_templates:
  - "quay.io/foroughfor/console:{{ .Tag }}-s390x"
  use: buildx
  goarch: s390x
  dockerfile: Dockerfile.release
  extra_files:
    - LICENSE
    - CREDITS
  build_flag_templates:
  - "--platform=linux/s390x"
  - "--build-arg=TAG={{ .Tag }}"
- image_templates:
  - "quay.io/foroughfor/console:{{ .Tag }}-arm64"
  use: buildx
  goarch: arm64
  goos: linux
  dockerfile: Dockerfile.release
  extra_files:
    - LICENSE
    - CREDITS
  build_flag_templates:
  - "--platform=linux/arm64"
  - "--build-arg=TAG={{ .Tag }}"
docker_manifests:
- name_template: foroughfor/console:{{ .Tag }}
  image_templates:
  - foroughfor/console:{{ .Tag }}-amd64
  - foroughfor/console:{{ .Tag }}-arm64
  - foroughfor/console:{{ .Tag }}-ppc64le
  - foroughfor/console:{{ .Tag }}-s390x
- name_template: quay.io/foroughfor/console:{{ .Tag }}
  image_templates:
  - quay.io/foroughfor/console:{{ .Tag }}-amd64
  - quay.io/foroughfor/console:{{ .Tag }}-arm64
  - quay.io/foroughfor/console:{{ .Tag }}-ppc64le
  - quay.io/foroughfor/console:{{ .Tag }}-s390x
- name_template: foroughfor/console:latest
  image_templates:
  - foroughfor/console:{{ .Tag }}-amd64
  - foroughfor/console:{{ .Tag }}-arm64
  - foroughfor/console:{{ .Tag }}-ppc64le
  - foroughfor/console:{{ .Tag }}-s390x
